linters:
  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  LeadingCommentSpace:
    enabled: false

  LineLength:
    max: 160

  RuboCop:
    enabled: true
    exclude:
      - app/views/kaminari/**/*
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/AlignParameters
      - Layout/IndentationWidth
      - Layout/LeadingCommentSpace
      - Layout/TrailingBlankLines
      - Layout/TrailingWhitespace
      - Metrics/BlockLength
      - Metrics/LineLength
      - Style/BlockNesting
      - Style/ElseAlignment
      - Style/EndOfLine
      - Style/FileName
      - Style/FinalNewline
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier

  SpaceInsideHashAttributes:
    enabled: false
